# permissions for end users to edit codebubbles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: codebubble-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bubblesopr
    app.kubernetes.io/part-of: bubblesopr
    app.kubernetes.io/managed-by: kustomize
  name: codebubble-editor-role
rules:
- apiGroups:
  - codebubble.bubbles.dev
  resources:
  - codebubbles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - codebubble.bubbles.dev
  resources:
  - codebubbles/status
  verbs:
  - get
